#!/bin/sh

echo "Running static analysis..."

# Format code using Flutter format than Analyze it according to pedantic rules
flutter format . && flutter analyze
status=$?
if [ "$status" = 0 ] ; then
    git add .
    echo "Static analysis found no problems. You can push your modifications safely"
    exit 0
else
    echo 1>&2 "Static analysis found violations it could not fix.\nCorrect the lines shown and commit again."
    exit 1
fi