name: repository
description: TACO repository
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.5.1
  pedantic: ^1.9.0
  sembast: ^2.4.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
