name: use_case
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

#flutter packages pub run build_runner build
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  repository:
    path: ../repository

  mobx: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0